server:
  port: 8081
spring:
  application:
    name: eurka-server
  security:
    user:
      name: hunter
      password: ht5828046
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/